### ISSUE TITLE
ATB.js compatibility issue with YEP_BattleEngineCore.js

### ISSUE THREAD

**Issue by RyanBram** [unagiootoro/RPGMV#1]
Hi.
In your latest update, I saw that you did so many fix in solving compatibility issue with YEP_BattleEngineCore.js.
But when I tried it in a fresh project I encounter issues like the following screenshot:

![ATB Screenshot](https://user-images.githubusercontent.com/4508389/90973398-e5dd1280-e54b-11ea-88f3-baa5976fadef.png)

I also attached the sample of the project here in case you want to investigate:
https://drive.google.com/file/d/1p3063eIATethq5_T_w9pYHgESRavP_NU/view?usp=sharing

Thank you very much for your attention.

**Comment by unagiootoro** [comment]
Thank you for issue report.
It seems that I changed the wrong part when I modified the string by batch replacement.
This problem has been fixed in the new version(v1.4.2).

**Comment by RyanBram** [comment]
Thank you very much for fixing the issue.

It looks like the compatibility issue are gone, so this plugin can be used alongside YEP_BattleEngineCore.js.

Best regards,
RyanBram
