### ISSUE TITLE
[Question] ATB.js

### ISSUE THREAD

**Issue by RyanBram** [unagiootoro/RPGMV#2]
こんにちは、うなぎおおとろ。

ATB.jsで実現した質問があります。

戦闘開始時に各アクターの初期ATBゲージをランダムに埋めるにはどうすればよいですか？ ATB.jsを試すと、すべてのアクターのゲージが常に0から始まるためです。 最初のゲージがランダムである方が良いと思うので、最速のアクターが常に最初に攻撃するとは限りません。

この素晴らしいプラグインをありがとう。 😄。

_ライアン_

---

Hi, うなぎおおとろ.

I have a question realted with ATB.js:

How to make initial ATB gauge for each actors at the start of battle to fill randomly? Because when I try ATB.js, the gauge will always start from 0 for every actor. I think it is better when the initial gauge is random, so the fastest actor doesn't always attack first.

Thank you for this wonderful plugin. 😄 .

_Ryan_

**Comment by unagiootoro** [comment]
最初のゲージは0から始まりますが、各バトラーの敏捷性は毎ターン開始時にランダムに補正が加えられるようになっています。そのため、必ず最速のアクターが最初に行動するとは限りません。

RPGツクールMZの発売に伴いこのプラグインは役目を終えました。RPGツクールMZではATBは最初から搭載されているため、今後はそちらのほうに注力していきます。
なのでRPGツクールMVでATBを利用される場合は別のプラグインの利用をお勧めします。

**Comment by RyanBram** [comment]
わかります。
ご回答どうもありがとうございました。
